In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("insurance (1).csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
df.duplicated().sum()

np.int64(1)

In [ ]:
df = df.drop_duplicates(keep=False)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [ ]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
df.shape

(1336, 7)

In [ ]:
from re import X
X = df [["age","sex","bmi","children","smoker","region"]]
Y = df [["charges"]]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, random_state=18)

In [ ]:
X['sex'] = le.fit_transform(X['sex'])
X['smoker'] = le.fit_transform(X['smoker'])
X['region'] = le.fit_transform(X['region'])

In [ ]:
X = pd.get_dummies(X, drop_first=True)

In [ ]:
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
model.coef_

array([[  258.99182175,  -151.22867191,   340.46166328,   569.08865464,
        23904.07353301,  -282.56827455]])

In [ ]:
model.intercept_

array([-12366.50212282])

In [ ]:
y_pred_train = model.predict(X_train)

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score
from math import sqrt

In [ ]:
sqrt(mean_squared_error(y_train, y_pred_train))

6182.706896750325

In [ ]:
r2_score(y_train, y_pred_train)

0.7529411564529758

In [ ]:
y_pred_test = model.predict(X_test)

In [ ]:
sqrt(mean_squared_error(y_test, y_pred_test))

5634.389818363172

In [ ]:
r2_score(y_test, y_pred_test)

0.736888417636729